export const environment = {
    production: false,
    loginUrl: 'http://localhost:8000/api/login',
    registerUrl: 'http://localhost:8000/api/register',
    apiUrl: 'http://localhost:8000/api',
    notificatioUrl:`http://localhost:8000/api/notifications`,
    adminNotificatioUrl:`http://localhost:8000/api/notifications/admin`,
    allOrdersUrl: 'http://localhost:8000/api/all-orders',
    futureOrdersUrl: 'http://localhost:8000/api/future-orders',
    pastOrdersUrl: 'http://localhost:8000/api/past-orders',
    CompletionFormUrl:'http://localhost:8000/api/complete-ride-form',
    socketUrl: 'http://localhost:8000',
    forgotPassUrl:'http://localhost:8000/api/forgot-password',
    resetPassUrl:'http://localhost:8000/api/reset-password',
    rideLocationsUrl:'http://localhost:8000/api/rides/with-locations',
    frozenVehiclesUrl:'http://localhost:8000/api/all-vehicles',
    vehicleUsageStatsUrl: 'http://localhost:8000/vehicles/usage-stats',
    vehicleStatsUrl: 'http://localhost:8000/api/vehicles/usage-stats',
    vehiclesTypes:'http://localhost:8000/api/vehicle-types',
    ridesSupposedToStartUrl:'http://localhost:8000/api/rides_supposed-to-start',
    noShowStatsUrl: 'http://localhost:8000/api/statistics/no-show',
    userRidesForExport: 'http://localhost:8000/api/analytics/user-rides',
    latestRequirementURL:'http://localhost:8000/api/latest-requirement',
    addReqConfirmationURL:'http://localhost:8000/api/confirm-requirements',
    allAuditLogsUrl: 'http://localhost:8000/api/all-audit-logs', 
    departmentsUrl: 'http://localhost:8000/api/departments',
    usersUrl: 'http://localhost:8000/api/users',
    getRequirementsUrl: 'http://localhost:8000/api/get-requirements',
    updateRequirementsUrl: 'http://localhost:8000/api/update-requirements',
    ordersBaseUrl: 'http://localhost:8000/api/orders',
    distanceUrl: 'http://localhost:8000/api/distance', 
    supervisorOrdersUrl: 'http://localhost:8000/api/supervisor-orders',
    ridesBaseUrl: 'http://localhost:8000/api/rides', 
    employeesByDepartmentUrl: 'http://localhost:8000/api/employees/by-department/',
    rolesUrl: 'http://localhost:8000/api/roles',
  };
  